import { randomUUID } from 'crypto';
import { Ledger } from '../../core/ledger.js';
import { toHub88Amount, fromHub88Amount } from './currency.js';

// Network-failure policy on top of walletClient's retry mechanism — see
// HUB88_INTEGRATION.md § Politique réseau Wallet API. A `bet` is never retried:
// on ambiguous outcome (we truly don't know if it landed) the safe move is a
// best-effort rollback of that same transaction_uuid, not a second attempt that
// could double-debit if the first one actually succeeded. `win`/`rollback` are
// themselves corrections — retrying them is safe (idempotent via transaction_uuid)
// and is exactly the recovery Hub88's docs describe for a transient network fault.
const WALLET_CORRECTION_RETRIES = 2;

// Hub88 aggregator platform's wallet backend — the operator (via Hub88) is
// authoritative on the balance, not us. Every method is a real signed HTTP call
// through `walletClient`; see server/core/ledger.js for the contract and
// HUB88_INTEGRATION.md § Changement architectural n°1 for why this differs so
// fundamentally from server/platforms/standalone/localLedger.js.
//
// `session` is the per-player context resolved from /game/url (see sessions.js):
// { gameCode, hub88Token, currency, user, ... }. It never changes for the lifetime
// of one Round — a new Hub88 launch (new /game/url call) makes a new session.
// Note: session.hub88Token (the *player's* token, sent to the Wallet API) is
// distinct from session.token (our own session key, socket.io-facing only) —
// see sessions.js for why these must never be conflated.
export class Hub88Ledger extends Ledger {
  constructor(walletClient, session) {
    super();
    this.walletClient = walletClient;
    this.session       = session;
  }

  _baseFields() {
    return {
      game_code: this.session.gameCode,
      token:     this.session.hub88Token,
      ...(this.session.supplierUser ? { supplier_user: this.session.supplierUser } : {}),
    };
  }

  async getBalance() {
    const res = await this.walletClient.post('/user/balance', this._baseFields());
    if (!res.ok) throw new Error(`Hub88 getBalance failed: ${res.error}`);
    return fromHub88Amount(res.data.balance);
  }

  // meta: { roundId, transactionUuid } — transactionUuid is generated by
  // roundEngine.js's Round.startRound and stored as lastBetTransactionUuid, so the
  // matching win/rollback call below can reference it.
  async debit(amount, meta = {}) {
    const res = await this.walletClient.post('/transaction/bet', {
      ...this._baseFields(),
      transaction_uuid: meta.transactionUuid,
      round:             meta.roundId,
      round_closed:      false, // the bet is never the round's last call in this game
      currency:           this.session.currency,
      amount:               toHub88Amount(amount),
    });
    if (res.ok) return { ok: true, balance: fromHub88Amount(res.data.balance) };

    // A parsed RS_ERROR_* (insufficient balance, limit reached, ...) is a
    // definitive answer — the balance never moved, nothing to unwind.
    if (res.error !== 'network_error') return { ok: false, error: res.error };

    // Ambiguous outcome: we don't know whether this bet actually landed on
    // Hub88's side before the connection dropped. Best-effort rollback of the
    // same transaction_uuid resolves it either way. 'transaction_not_found' is
    // the *expected*, routine resolution — it means the bet genuinely never
    // reached Hub88, nothing to undo, not a failure worth alarming on. Any other
    // failure here is the real problem: the bet may have landed and we still
    // couldn't undo it, which needs a human to reconcile against Hub88 directly.
    const cleanup = await this.rollback({ transactionUuid: meta.transactionUuid });
    if (!cleanup.ok && cleanup.error !== 'transaction_not_found') {
      console.error(
        `[hub88Ledger] bet ${meta.transactionUuid} failed on a network error and the follow-up rollback also failed (${cleanup.error}) — manual reconciliation may be needed.`,
      );
    }
    return { ok: false, error: 'network_error' };
  }

  // meta: { roundId, transactionUuid, referenceTransactionUuid, roundClosed }
  // amount 0 is valid and expected on a bust — Hub88 requires a win call with
  // round_closed:true to settle the round even when there's nothing to pay out
  // (see roundEngine.js's step_ bust branch).
  async credit(amount, meta = {}) {
    const res = await this.walletClient.post('/transaction/win', {
      ...this._baseFields(),
      transaction_uuid:            meta.transactionUuid,
      reference_transaction_uuid: meta.referenceTransactionUuid,
      round:                        meta.roundId,
      round_closed:                  meta.roundClosed ?? true,
      currency:                        this.session.currency,
      amount:                            toHub88Amount(amount),
    }, { retries: WALLET_CORRECTION_RETRIES });
    if (!res.ok) return { ok: false, error: res.error };
    return { ok: true, balance: fromHub88Amount(res.data.balance) };
  }

  // meta: { transactionUuid } — the bet's transaction_uuid to undo (roundEngine.js
  // passes lastBetTransactionUuid as referenceTransactionUuid here for symmetry
  // with credit's meta shape).
  async rollback(meta = {}) {
    const res = await this.walletClient.post('/transaction/rollback', {
      ...this._baseFields(),
      transaction_uuid:            randomUUID(),
      reference_transaction_uuid: meta.transactionUuid ?? meta.referenceTransactionUuid,
    }, { retries: WALLET_CORRECTION_RETRIES });
    if (!res.ok) return { ok: false, error: res.error };
    return { ok: true, balance: res.data.balance != null ? fromHub88Amount(res.data.balance) : undefined };
  }
}
